sources:
  # Clash 类型（优先推荐）
  - name: snakem982_clash_meta
    url: https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta.yaml
    type: clash
  - name: snakem982_clash_meta_2
    url: https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta-2.yaml
    type: clash
  - name: mfuu_clash
    url: https://raw.githubusercontent.com/mfuu/v2ray/master/clash.yaml
    type: clash
  - name: anaer_clash
    url: https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml
    type: clash
  - name: ermaozi_clash
    url: https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
    type: clash
  - name: SnapdragonLee_clash
    url: https://raw.githubusercontent.com/SnapdragonLee/SystemProxy/master/dist/clash_config.yaml
    type: clash

  # V2Ray Base64 类型
  - name: mfuu_v2ray
    url: https://raw.githubusercontent.com/mfuu/v2ray/master/v2ray
    type: v2ray_base64
  - name: ermaozi_v2ray
    url: https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/v2ray.txt
    type: v2ray_base64
  - name: barry_far_v2ray
    url: https://raw.githubusercontent.com/barry-far/V2ray-Config/main/All_Configs_Sub.txt
    type: v2ray_base64

  # Telegram 网页抓取===

  #更多优质代理池（Clash 类型）===
  - name: caijh_eternity_clash
    url: https://raw.githubusercontent.com/caijh/FreeProxiesScraper/master/Eternity.yaml
    type: clash
  - name: Ruk1ng_freeSub_clash
    url: https://raw.githubusercontent.com/Ruk1ng001/freeSub/main/clash.yaml
    type: clash
  - name: free18_v2ray_clash
    url: https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml
    type: clash
  # V2Ray Base64
  - name: barry_far_all_configs
    url: https://raw.githubusercontent.com/barry-far/V2ray-Config/main/All_Configs_Sub.txt
    type: v2ray_base64
  - name: MatinGhanbari_all_sub
    url: https://raw.githubusercontent.com/MatinGhanbari/v2ray-configs/main/subscriptions/v2ray/all_sub.txt
    type: v2ray_base64
  - name: ebrasha_all_configs
    url: https://raw.githubusercontent.com/ebrasha/free-v2ray-public-list/refs/heads/main/all_extracted_configs.txt
    type: v2ray_base64
  - name: Delta_Kronecker_sub
    url: https://raw.githubusercontent.com/Delta-Kronecker/V2ray-Config/main/sub.txt
    type: v2ray_base64
  - name: Pawdroid_free_servers   # 经典老牌
    url: https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub
    type: v2ray_base64